default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["HOST"] %>
  port: 5432

development:
  <<: *default
  database: moto_life_development

test:
  <<: *default
  database: moto_life_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  database: <%= ENV["MYSQL_DATABASE"] %>
  username: <%= ENV["MYSQL_USERNAME"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  socket: <%= ENV["MYSQL_SOCKET"] %>